In [1]:
import numpy as np
import pandas as pd
import matplotlib as plt
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# null hypothesis- one categorical
# from scipy import stats

# F, p = stats.f_oneway(red_wine[red_wine['quality_label'] == 'low']['alcohol'],
# red_wine[red_wine['quality_label'] == 'medium']['alcohol'],
# red_wine[red_wine['quality_label'] == 'high']['alcohol'])
# print('ANOVA test for mean alcohol levels across wine samples with different quality ratings')
# print('F Statistic:', F, '\tp-value:', p)

## Data Preparatrion

In [3]:
red_wine_heatmap = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv', sep=';')
white_wine_heatmap = pd.read_csv('winequality-white.csv', sep=';')

In [4]:
white_wine_heatmap

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.0              0.27         0.36            20.7      0.045   
1               6.3              0.30         0.34             1.6      0.049   
2               8.1              0.28         0.40             6.9      0.050   
3               7.2              0.23         0.32             8.5      0.058   
4               7.2              0.23         0.32             8.5      0.058   
...             ...               ...          ...             ...        ...   
4893            6.2              0.21         0.29             1.6      0.039   
4894            6.6              0.32         0.36             8.0      0.047   
4895            6.5              0.24         0.19             1.2      0.041   
4896            5.5              0.29         0.30             1.1      0.022   
4897            6.0              0.21         0.38             0.8      0.020   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    45.0                 170.0  1.00100  3.00       0.45   
1                    14.0                 132.0  0.99400  3.30       0.49   
2                    30.0                  97.0  0.99510  3.26       0.44   
3                    47.0                 186.0  0.99560  3.19       0.40   
4                    47.0                 186.0  0.99560  3.19       0.40   
...                   ...                   ...      ...   ...        ...   
4893                 24.0                  92.0  0.99114  3.27       0.50   
4894                 57.0                 168.0  0.99490  3.15       0.46   
4895                 30.0                 111.0  0.99254  2.99       0.46   
4896                 20.0                 110.0  0.98869  3.34       0.38   
4897                 22.0                  98.0  0.98941  3.26       0.32   

      alcohol  quality  
0         8.8        6  
1         9.5        6  
2        10.1        6  
3         9.9        6  
4         9.9        6  
...       ...      ...  
4893     11.2        6  
4894      9.6        5  
4895      9.4        6  
4896     12.8        7  
4897     11.8        6  

[4898 rows x 12 columns]

## dropping duplicates and concatinating

In [5]:
white_wine_heatmap.drop_duplicates(inplace=True)
red_wine_heatmap.drop_duplicates(inplace=True)
white_wine_heatmap.reset_index(inplace=True)
red_wine_heatmap.reset_index(inplace=True)
red_wine_heatmap.drop(columns='index', inplace=True)
white_wine_heatmap.drop(columns='index', inplace=True)

In [6]:
# add column wine type
red_wine_heatmap['wine type']='red'
white_wine_heatmap['wine type']='white'
wine=pd.concat([red_wine_heatmap, white_wine_heatmap], ignore_index=True)
wine

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4              0.70         0.00             1.9      0.076   
1               7.8              0.88         0.00             2.6      0.098   
2               7.8              0.76         0.04             2.3      0.092   
3              11.2              0.28         0.56             1.9      0.075   
4               7.4              0.66         0.00             1.8      0.075   
...             ...               ...          ...             ...        ...   
5315            6.2              0.21         0.29             1.6      0.039   
5316            6.6              0.32         0.36             8.0      0.047   
5317            6.5              0.24         0.19             1.2      0.041   
5318            5.5              0.29         0.30             1.1      0.022   
5319            6.0              0.21         0.38             0.8      0.020   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    13.0                  40.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
5315                 24.0                  92.0  0.99114  3.27       0.50   
5316                 57.0                 168.0  0.99490  3.15       0.46   
5317                 30.0                 111.0  0.99254  2.99       0.46   
5318                 20.0                 110.0  0.98869  3.34       0.38   
5319                 22.0                  98.0  0.98941  3.26       0.32   

      alcohol  quality wine type  
0         9.4        5       red  
1         9.8        5       red  
2         9.8        5       red  
3         9.8        6       red  
4         9.4        5       red  
...       ...      ...       ...  
5315     11.2        6     white  
5316      9.6        5     white  
5317      9.4        6     white  
5318     12.8        7     white  
5319     11.8        6     white  

[5320 rows x 13 columns]

In [7]:
numeric_wine=wine.iloc[:, 0:12]
corr=numeric_wine.corr()
corr

fixed acidity  volatile acidity  citric acid  \
fixed acidity              1.000000          0.214752     0.330328   
volatile acidity           0.214752          1.000000    -0.384192   
citric acid                0.330328         -0.384192     1.000000   
residual sugar            -0.104439         -0.163696     0.146189   
chlorides                  0.288918          0.367626     0.055199   
free sulfur dioxide       -0.281590         -0.349039     0.130849   
total sulfur dioxide      -0.327471         -0.400716     0.194835   
density                    0.478180          0.308452     0.094758   
pH                        -0.271182          0.246687    -0.344735   
sulphates                  0.304844          0.227772     0.059183   
alcohol                   -0.102573         -0.065411    -0.005496   
quality                   -0.080092         -0.265205     0.097954   

                      residual sugar  chlorides  free sulfur dioxide  \
fixed acidity              -0.104439   0.288918            -0.281590   
volatile acidity           -0.163696   0.367626            -0.349039   
citric acid                 0.146189   0.055199             0.130849   
residual sugar              1.000000  -0.123094             0.398717   
chlorides                  -0.123094   1.000000            -0.186615   
free sulfur dioxide         0.398717  -0.186615             1.000000   
total sulfur dioxide        0.487519  -0.269817             0.720488   
density                     0.520930   0.371867             0.006166   
pH                         -0.234522   0.025823            -0.141747   
sulphates                  -0.174717   0.405051            -0.198244   
alcohol                    -0.305242  -0.269601            -0.170012   
quality                    -0.056830  -0.202137             0.054002   

                      total sulfur dioxide   density        pH  sulphates  \
fixed acidity                    -0.327471  0.478180 -0.271182   0.304844   
volatile acidity                 -0.400716  0.308452  0.246687   0.227772   
citric acid                       0.194835  0.094758 -0.344735   0.059183   
residual sugar                    0.487519  0.520930 -0.234522  -0.174717   
chlorides                        -0.269817  0.371867  0.025823   0.405051   
free sulfur dioxide               0.720488  0.006166 -0.141747  -0.198244   
total sulfur dioxide              1.000000  0.006711 -0.222956  -0.275836   
density                           0.006711  1.000000  0.034273   0.282690   
pH                               -0.222956  0.034273  1.000000   0.168150   
sulphates                        -0.275836  0.282690  0.168150   1.000000   
alcohol                          -0.249004 -0.667811  0.097314  -0.017232   
quality                          -0.050296 -0.326434  0.039733   0.041884   

                       alcohol   quality  
fixed acidity        -0.102573 -0.080092  
volatile acidity     -0.065411 -0.265205  
citric acid          -0.005496  0.097954  
residual sugar       -0.305242 -0.056830  
chlorides            -0.269601 -0.202137  
free sulfur dioxide  -0.170012  0.054002  
total sulfur dioxide -0.249004 -0.050296  
density              -0.667811 -0.326434  
pH                    0.097314  0.039733  
sulphates            -0.017232  0.041884  
alcohol               1.000000  0.469422  
quality               0.469422  1.000000

## add quality label

In [8]:
# we are creating a new column called "quality_label", we define a range and associate that range with a label
wine['quality label'] = wine['quality'].apply(lambda value: 'low'
if value <= 5 else 'medium'
if value <= 7 else 'high')

# here we are transforming these labels into categrical data type (specific to pandas) instead of simple string
wine['quality label'] = pd.Categorical(wine['quality label'],
categories=['low', 'medium', 'high'])
# wine.drop('quality_label',inplace=True, axis=1)

In [9]:
wine.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.66         0.00             1.8      0.075   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 13.0                  40.0   0.9978  3.51       0.56   

   alcohol  quality wine type quality label  
0      9.4        5       red           low  
1      9.8        5       red           low  
2      9.8        5       red           low  
3      9.8        6       red        medium  
4      9.4        5       red           low

# hypothesis check

In [10]:
from scipy import stats

In [11]:
def anova_tests2(df):  
    
    features = ['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol']
    
    for feature in features:
        F, p = stats.f_oneway(
            df[df['quality label'] == 'low'][feature],
            df[df['quality label'] == 'medium'][feature],
            df[df['quality label'] == 'high'][feature]
        )
        if p > 0.05:
         print(f"ANOVA test for mean {feature} across wine samples with different quality ratings")
         print('F Statistic:', F, '\tp-value:', p)
        else:
         print("there is correlation")

In [12]:
anova_tests2(wine)

there is correlation
there is correlation
there is correlation
there is correlation
there is correlation
there is correlation
there is correlation
there is correlation
there is correlation
there is correlation
there is correlation


In [13]:
wine.head(1)

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4               0.7          0.0             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality wine type quality label  
0      9.4        5       red           low

In [14]:
# changing wine type to 0 and 1
wine1=wine.copy()

## encoding and removing unnecessary columns

In [15]:
wine1['wine type'].replace(['red', 'white'],
                        [0, 1], inplace=True)

In [16]:
from sklearn.preprocessing import OrdinalEncoder
# Create an instance of OrdinalEncoder

In [17]:
ordinal_encoder = OrdinalEncoder(categories=[['low', 'medium', 'high']])
wine1['NumericalLabels'] = ordinal_encoder.fit_transform(wine1[['quality label']])

In [18]:
wine1.drop(columns='quality', inplace=True)

In [19]:
wine1.drop(columns='quality label', inplace=True)

In [20]:
wine1.drop(columns='wine type', inplace=True)

# Models

## Logistic Regression Mathod

### divide into train and test

In [21]:
#importm library for dicidint the dataset into two 
from sklearn.model_selection import train_test_split

In [22]:
wine1.head(1)

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4               0.7          0.0             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  NumericalLabels  
0      9.4              0.0

In [23]:
wine2=wine1.copy()

In [24]:
wine2.drop(columns='NumericalLabels', inplace=True)

In [25]:
X=wine2

In [26]:

y = wine1['NumericalLabels']  # --> what you're trying to predict
  # --> the features we will keep to build our model





In [27]:
X.shape

(5320, 11)

In [28]:
y.shape

(5320,)

In [29]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=100)

In [30]:
y_test.shape

(1064,)

In [31]:
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(4256, 11) (1064, 11) (4256,) (1064,)


### building model Logistic Regression

In [32]:
#building model Logistic Regression

from sklearn.linear_model import LogisticRegression

In [33]:
logistics_regression_model=LogisticRegression(random_state=52)

In [34]:
#fit the model
logistics_regression_model.fit(X_train, y_train)

c:\Users\gabb_\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(random_state=52)

In [35]:
# prediction
predictions=logistics_regression_model.predict(X_test)

In [36]:
predictions

array([0., 1., 1., ..., 1., 0., 1.])

In [37]:
from sklearn.metrics import accuracy_score

In [38]:
acc=accuracy_score(y_test, predictions)
acc

0.6804511278195489

### results

In [39]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [40]:
accuracy = accuracy_score(y_test, predictions)
print(f"Accuracy: {accuracy}")

print("\nClassification Report:")
print(classification_report(y_test, predictions))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, predictions))

Accuracy: 0.6804511278195489

Classification Report:
              precision    recall  f1-score   support

         0.0       0.67      0.53      0.59       414
         1.0       0.69      0.82      0.75       614
         2.0       0.00      0.00      0.00        36

    accuracy                           0.68      1064
   macro avg       0.45      0.45      0.45      1064
weighted avg       0.66      0.68      0.66      1064


Confusion Matrix:
[[219 195   0]
 [109 505   0]
 [  0  36   0]]


c:\Users\gabb_\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\gabb_\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\gabb_\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


## Random Forest model

In [41]:
from sklearn.ensemble import RandomForestClassifier


In [42]:
RF_model= RandomForestClassifier(n_estimators= 100, criterion='entropy', random_state=445)

In [43]:
RF_model.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', random_state=445)

In [44]:
preds2= RF_model.predict(X_test)

In [45]:
preds2

array([0., 0., 1., ..., 1., 0., 1.])

In [46]:
acc=accuracy_score(y_test, preds2)
acc

0.7274436090225563

### results

In [47]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [48]:
accuracy = accuracy_score(y_test, preds2)
print(f"Accuracy: {accuracy}")

print("\nClassification Report:")
print(classification_report(y_test, preds2))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, preds2))

Accuracy: 0.7274436090225563

Classification Report:
              precision    recall  f1-score   support

         0.0       0.70      0.66      0.68       414
         1.0       0.74      0.81      0.78       614
         2.0       1.00      0.03      0.05        36

    accuracy                           0.73      1064
   macro avg       0.81      0.50      0.50      1064
weighted avg       0.74      0.73      0.71      1064


Confusion Matrix:
[[273 141   0]
 [114 500   0]
 [  1  34   1]]


## KNN

In [49]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [50]:
scaler = StandardScaler()
X_train1 = scaler.fit_transform(X_train)
X_test1 = scaler.transform(X_test)

In [51]:
k = 3  # You can adjust this value based on your problem
knn_model = KNeighborsClassifier(n_neighbors=k)
knn_model.fit(X_train1, y_train)

KNeighborsClassifier(n_neighbors=3)

In [52]:
y_pred = knn_model.predict(X_test1)

### results

In [53]:
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.6983082706766918

Classification Report:
              precision    recall  f1-score   support

         0.0       0.66      0.64      0.65       414
         1.0       0.72      0.78      0.75       614
         2.0       0.60      0.08      0.15        36

    accuracy                           0.70      1064
   macro avg       0.66      0.50      0.51      1064
weighted avg       0.69      0.70      0.69      1064


Confusion Matrix:
[[263 151   0]
 [135 477   2]
 [  3  30   3]]


# Support Vector Machines (SVM)

In [54]:
# Import necessary libraries
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report


In [55]:
X4=wine2
y4 = wine1['NumericalLabels']  # --> what you're trying to predict
  # --> the features we will keep to build our model

In [56]:
from sklearn.model_selection import train_test_split
X4_train, X4_test, y4_train, y4_test = train_test_split(X4,y4,test_size=0.2, random_state=100)

# Standardize the features (important for SVM)
scaler = StandardScaler()
X4_train = scaler.fit_transform(X4_train)
X4_test = scaler.transform(X4_test)

In [57]:
# Initialize the SVM classifier
svm_classifier = SVC(kernel='linear', C=1.0, random_state=42)

In [58]:


# Train the SVM classifier
svm_classifier.fit(X4_train, y4_train)

# Make predictions on the test set
prediction4 = svm_classifier.predict(X4_test)

In [59]:
# Evaluate the performance of the classifier
accuracy4 = accuracy_score(y4_test, prediction4)
report4 = classification_report(y4_test, prediction4)

# Print the results
print(f"Accuracy: {accuracy4:.2f}")
print("\nClassification Report:\n", report4)

Accuracy: 0.71

Classification Report:
               precision    recall  f1-score   support

         0.0       0.70      0.61      0.65       414
         1.0       0.72      0.82      0.77       614
         2.0       0.00      0.00      0.00        36

    accuracy                           0.71      1064
   macro avg       0.47      0.48      0.47      1064
weighted avg       0.69      0.71      0.70      1064



c:\Users\gabb_\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\gabb_\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\gabb_\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
